#!/bin/bash
source /etc/default/composite
case `xdriinfo` in
	*radeon*)
		exec $radeon $@
	;;
	*i965*)
		exec $i965 $@
	;;
	*nouveau*)
		exec $nouveau $@
	;;
	*nvidia*)
		exec $nvidia $@
	;;
	*not*)
		exit
	;;
	*old*)
		exit
	;;
esac
